### ISSUE TITLE
not release tag

### ISSUE THREAD

**Issue by recherst** [huynguyencong/ToastSwiftUI#1]
when i add dependency using swift package manager it notices that not have a release version.

**Comment by huynguyencong** [comment]
Added. Thank you!
It was not cause error when you add SPM, wasn't it?

**Comment by recherst** [comment]
Yes, that's right!

**Comment by jeanmartin** [comment]
For whatever reason this still is not working. Adding your repo in SPM it can't find any version number. Entering 0.2 manually then throws errors.

**Comment by huynguyencong** [comment]
Updated. It should be 0.2.0 instead of 0.2.

**Comment by huynguyencong** [comment]
Please try again!
