### ISSUE TITLE
The Show POP don't work

### ISSUE THREAD

**Issue by garygng** [huynguyencong/ToastSwiftUI#2]
<img width="752" alt="Screenshot 2021-09-15 at 3 26 28 PM" src="https://user-images.githubusercontent.com/16561835/133389630-f56c2497-21c4-4e40-9a59-f277b8432ce0.png">

Can you fix it?

**Comment by huynguyencong** [comment]
It is not my example project, is it? `MyPopup` is a custom class of example project. You should replace it by `your pop` up in your project.
